### ISSUE TITLE
Category method names need to be namespaced (prefixed)

### ISSUE THREAD

**Issue by snej** [khanlou/Objective-Shorthand#7]
None of the category methods introduced in this API have any unique namespace prefixes. For instance, the NSString method `-matchesRegex:` should properly be named something like `os_matchesRegex:`.

See Apple's documentation on [Avoiding Category Method Name Clashes](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/CustomizingExistingClasses/CustomizingExistingClasses.html#//apple_ref/doc/uid/TP40011210-CH6-SW4):

>In order to avoid undefined behavior, it’s best practice to add a prefix to method names in categories on framework classes, just like you should add a prefix to the names of your own classes. You might choose to use the same three letters you use for your class prefixes, but lowercase to follow the usual convention for method names, then an underscore, before the rest of the method name.

NSHipster has a good description of the problem in their blog post on [Namespacing](http://nshipster.com/namespacing/) (see the section "Method Prefixes".)

This is especially problematic in the cases where you've added category methods on iOS where methods with the same names already exist on OS X, for example `NSComparisonMethods`. It seems entirely possible that Apple will bring those methods over to iOS at some point, at which point it's undefined which implementation will be called.

I'm not just being paranoid in calling this out. I assure you I _have_ seen this cause bugs before, when a new OS release from Apple added a method that I was already using in my own category. And it did create a crash in my app, which was rather difficult to track down because my expectations about what my code was doing were of course completely wrong.

**Comment by khanlou** [comment]
I think Mattt makes a fine case. He says the benefit to method prefixing isn't obvious:

> Collisions can be detected at compile time by setting the `OBJC_PRINT_REPLACED_METHODS` environment variable to YES. In practice, collisions are extremely rare, and when they do occur, they're usually an indicator of functionality that is needlessly duplicated across dependencies. Although the worst-case scenario is a runtime exception, it's entirely likely that two methods named the same thing will actually do the same thing, and result in no change in behavior. All of those Swiss Army Knife categories that defined NSArray `-firstObject` continued to march on once the method was officially added.

The spirit of this pod is to fill in the gaps left by Foundation, not just to provide a bunch of utility functions. If there were a really bad collision, I would definitely consider adding namespacing to the methods in Objective-Shorthand, but I think for right now, we're just hunting for problems.
